### PR TITLE
Reproducibility Updates

### PR DESCRIPTION
**Pull request by cansavvy**
Adding some reproducibility updates. 

Adding a few more tidbits here. 

I knitted things by hand because `make labs` wouldn't work. 
```
Rscript -e "remotes::install_github('muschellij2/jhur')"
``` 
won't install which is required by this. 
```
Downloading GitHub repo muschellij2/jhur@HEAD
Error: Failed to install 'jhur' from GitHub:
  missing value where TRUE/FALSE needed
Execution halted
```

### CODE REVIEW

**Comment by carriewright11** [comment]
Looks good so far! Indeed I think we could simplify how things are rendered, but we were going with how it was previously done. is that error from using the make command in the main directory? luckily it is still working for me - what we did last time is the other instructors made edits to the respective rmd files and then I rendered everything to avoid conflicts as well.

**Comment by cansavvy** [comment]
>  is that error from using the make command in the main directory?

Yes. Although it should be able to install from anywhere.

**Comment by carriewright11** [comment]
> > is that error from using the make command in the main directory?
> 
> Yes. Although it should be able to install from anywhere.

I guess we should check his code and file a PR if we can figure it out

**Review by carriewright11 — APPROVED** [review]
Looks good!

**Comment by carriewright11** [comment]
I see that you went with a different final rendered version without slides- was there a reason for that? Just curious.  Also would it be ok if I add one or more of your cartoons from your course?

**Pull request merged**
