### PR TITLE
Syllabus sections

### PR DESCRIPTION
**Pull request by carriewright11**
I thought it might make it easier for people to find certain information if we added some more section headers to the syllabus and also making it a tad more concise. I also collapsed the zoom instructions because it seems like most people know them now and we had discussed doing this at one point. @avahoffman what do you think of this?

Will need to merge in main after Ava's other PR #359 for date of R version.

### CODE REVIEW

**Comment by avahoffman** [comment]
Yeah, love it! Maybe can we make this stand out a bit more, maybe like a URL? Worried they might not realize it's clickable.

image

**Comment by carriewright11** [comment]
I made it blue like the link color - this is the local render with the triangle : 
Screenshot 2023-06-06 at 12 16 38 PM

Does that work?

**Comment by carriewright11** [comment]
made it bold too:
Screenshot 2023-06-06 at 12 22 29 PM

**Comment by avahoffman** [comment]
Yeah looks great!

**Review by avahoffman — APPROVED** [review]

**Pull request merged**
