### PR TITLE
removing the confusing dollar sign

### LINKED ISSUE #489: HW 2 confusion
#9 remove the $ in $5000 so that people don't get confused

### LINKED ISSUE #519: consistently using either "-" or "!" to not select columns or first introduce both
I used "-" when not selecting in the subsetting lecture - and noticed I used "!" in cleaning and wrote an issue  to myself to change it to "-"

However, I noticed there is a slide about not selecting columns using "!" in manipulating data (and some lab questions), do we just want to go with one method? or should we introduce both in the subsetting lecture instead?

### PR DESCRIPTION
**Pull request by carriewright11**
resolves #489 

removing the $ ... people tried to use it

resolves #519

more consistent use of `!` instead of `-` to remove columns (I mentioned `-`)

### CODE REVIEW

**Comment by carriewright11** [comment]
anyone understand the error @cansavvy or @avahoffman ?
Screenshot 2024-03-12 at 11 18 14 PM

It's strange cause we didn't move the files and did not get this error before but maybe it is because of updates to the PDF rendering.

**Comment by avahoffman** [comment]
Raised the issue in #552

**Comment by avahoffman** [comment]
I think the rendering issue is fixed. The problem is it was looking at homeworks and trying to make pdfs.. which doesn't really make sense!

**Comment by carriewright11** [comment]
@avahoffman  are you ok merging this and then fixing the conflicts in the subsetting branch you made or what would you like to do

**Comment by avahoffman** [comment]
Yes, let's merge this!

**Pull request merged**
