### PR TITLE
updating data viz module 

### LINKED ISSUE #227: Cool ggplot analogy with cake!
https://twitter.com/tanya_shapiro/status/1576935152575340544
image

### PR DESCRIPTION
**Pull request by padmashris**
updated most suggestions from #210 and resolved #227

### CODE REVIEW

**Comment by carriewright11** [comment]
Thank you @padmashris, this looks great - I will fix the spelling errors here.

**Comment by padmashris** [comment]
> Thank you @padmashris, this looks great - I will fix the spelling errors here.

thanks!

**Comment by carriewright11** [comment]
OK this now resolves #210

**Comment by carriewright11** [comment]
@padmashris I did the rest of the updates but you can make more changes if you wish

**Pull request merged**
