### PR TITLE
Subsetting table

### PR DESCRIPTION
**Pull request by carriewright11**
Not sure if this is what you had in mind @avahoffman, but adding a table for the subsetting lecture and will also try to do a table  for the current resource on when to use what

### CODE REVIEW

**Comment by avahoffman** [comment]
I like this and I think it will help folks. But in #304 I was referring to how different functions have different behavior. Especially `filter()`. If you do something like `mtcars %>% filter("mpg" > 30)` it doesn't work as expected.

**Comment by carriewright11** [comment]
> I like this and I think it will help folks. But in #304 I was referring to how different functions have different behavior. Especially `filter()`. If you do something like `mtcars %>% filter("mpg" > 30)` it doesn't work as expected.

gotcha - will keep working on this

**Comment by carriewright11** [comment]
@avahoffman how is this for the lecture?

**Comment by carriewright11** [comment]
I actually removed the table - cause I don't want to add too many details about conventions at this point

**Pull request merged**
