### PR TITLE
DATA IO updates

### LINKED ISSUE #173: Data IO notes
- we could slightly add more info about terms like string and character - or replace them 
- could use  https://cran.r-project.org/web/packages/OCSdata/vignettes/instructions.html#raw  to get the data set up in a similar manner so people are set up the same
- maybe make a visual about how data should be set up - where files should live relative to eachother
- could maybe remove the tibble description in Data IO - because we will do that later in depth? or I could remove it from data subsetting/data classes
- more discussion about different data types in data io? pointing people to `foreign` for spss users could also help but we already have haven
- could also show how to use  file --> import Dataset when people can't find files on their machine

### LINKED ISSUE #186: Move Data IO to later in the class
it's scary

### LINKED ISSUE #187: Data IO: Get rid of `spec()`?
I feel like this function isn't generalizeable enough, and perhaps they're better off focusing on `str()` ... Perhaps we mention spec once and leave it at that. thoughts?

`spec()` appears in the following:

./modules/Data_IO/Data_IO.Rmd
./modules/Data_IO/lab/Data_IO_Lab.Rmd
./modules/Data_IO/lab/Data_IO_Lab_Key.Rmd
./modules/HW/homework2_key.Rmd
./modules/HW/homework2.Rmd
./modules/cheatsheets/Day-2.md

### LINKED ISSUE #261: describe how you can see data variables in environment:
I think "describe how you can see data variables in environment: Click the play button on the lefthand side of the dataset under “Data” in the environment" should be done in a different lecture... maybe data IO? @avahoffman what do you think?

_Originally posted by @carriewright11 in https://github.com/jhudsl/intro_to_r/issues/174#issuecomment-1369318836_

### PR DESCRIPTION
**Pull request by avahoffman**
Major changes:

- adding information about how to import using the dropdown menu
- Showing that you can view objects from the environment
- remove `problems()` and `spec()`

Resolves #173 
Resolves #187
Resolves #186 
Resolves #261

### CODE REVIEW

**Comment by carriewright11** [comment]
I think we might have spec() later in other slides too - so we might want to watch out for that

**Comment by avahoffman** [comment]
> I think we might have spec() later in other slides too - so we might want to watch out for that

I did a regex so I think I caught them all :)

**Comment by carriewright11** [comment]
> > I think we might have spec() later in other slides too - so we might want to watch out for that
> 
> I did a regex so I think I caught them all :)

oh cool!

**Comment by avahoffman** [comment]
Ugh I guess I'll delete the Data_IO module from main 😜

**Pull request merged**
