### PR TITLE
adding links to summer 23

### LINKED ISSUE #413: add this to resources? people always ask about names
https://www.statworx.com/en/content-hub/blog/why-is-it-called-that-way-origin-and-meaning-of-r-package-names/

### LINKED ISSUE #424: Website Schedule
Day overview:
says EST but should be ET to be more flexible for EDT
Maybe add that timing will be approximate

### LINKED ISSUE #444: data options
the package `catdata` has some cool datasets - could at least add this to the project page or might want to use for other examples

### PR DESCRIPTION
**Pull request by avahoffman**
Woo!!! go team!

fyi @clifmckee 

Also, a final detail resolves #424 

Reorg and a few additions resolves #444 

Additional link resolves #413

### CODE REVIEW

**Comment by carriewright11** [comment]
Looks good to me!

**Comment by carriewright11** [comment]
Thank you for doing so much work to get these ready, @avahoffman !

**Comment by carriewright11** [comment]
Do we want to add winter 2023 at some point ( i dont think there is a rush at all - and I'd be happy to help)

**Comment by avahoffman** [comment]
> Do we want to add winter 2023 at some point ( i dont think there is a rush at all - and I'd be happy to help)

I haven't edited them and it does take a fair amount of time. I figure since there is something newer out, there isn't really a need to.

**Pull request merged**
