### PR TITLE
Working on a solution to manual updates

### PR DESCRIPTION
**Pull request by avahoffman**

### CODE REVIEW

**Comment by carriewright11** [comment]
Love this idea!

We will want to switch out the holiday too

**Comment by avahoffman** [comment]
> Love this idea!
> 
> We will want to switch out the holiday too

On it!

**Comment by carriewright11** [comment]
Love this so much! My issue #256  might help guide where we need this elsewhere.

**Comment by avahoffman** [comment]
Thanks! I think we can make this more extensive and integrated with the individual slides too. Okay merging for now and adding to it later?

**Comment by carriewright11** [comment]
> Thanks! I think we can make this more extensive and integrated with the individual slides too. Okay merging for now and adding to it later?

sure! just might want an issue to remind ourselves (maybe you already did that though - I am catching up :P)

**Review by carriewright11 — COMMENTED** [review]
Looks good :)

**Pull request merged**
