### PR TITLE
Pull resource

### LINKED ISSUE #428: `setdiff()` -- why need to pull if it is a dplyr function ? Is there a base and tidyverse version?

### PR DESCRIPTION
**Pull request by carriewright11**
people are confused about when they need to pull first for certain functions

Will resolve #428 and #427

### CODE REVIEW

**Comment by carriewright11** [comment]
@avahoffman idk if I made what you had more confusing or not - so it would be worth having you take a look :P 

I think when you use base::setdiff() without pulling it just gives you the first tibble but not sure.

**Comment by avahoffman** [comment]
Looks fantastic! 

- can we add a link to the rendered html under resources (perhaps under cheatsheets?)
- can we put this in the resources directory to keep things organized? Or do you want it somewhere else?

**Comment by carriewright11** [comment]
> Looks fantastic!
> 
> * can we add a link to the rendered html under resources (perhaps under cheatsheets?)
> * can we put this in the resources directory to keep things organized? Or do you want it somewhere else?

totally! I might try to organize the resource tab a bit too

**Comment by carriewright11** [comment]
> hmmm not sure how to improve the navigation of the resource page... I tried a toc but idk if that is better ... maybe we need tabs within this page or something?

I love it! hope you do too!

**Pull request merged**
